name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Install libusb, libudev (linux)
        run: |
          sudo apt update
          sudo apt install -y libusb-1.0-0-dev libudev-dev

      - uses: actions/checkout@v2

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1.3.0
        
      # - name: Build
      #   run: |
      #     cargo build --manifest-path teleprobe/Cargo.toml
      #     cargo build --manifest-path teleprobe/Cargo.toml --release
      #     cargo test --manifest-path teleprobe/Cargo.toml
      #     cargo test --manifest-path teleprobe/Cargo.toml --release

      - name: Install cargo-deb
        run: |
          cargo install cargo-deb

      - name: Build Debian Package
        run: |
          cargo deb --manifest-path teleprobe/Cargo.toml

      - name: Upload Debian Package
        uses: actions/upload-artifact@v4
        with:
          name: teleprobe-aarch64
          path: teleprobe/target/debian/*.deb
